apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-xe-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/oracle-xe
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-xe-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-xe
  labels:
    app: oracle-xe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-xe
  template:
    metadata:
      labels:
        app: oracle-xe
    spec:
      containers:
      - name: oracle-xe
        image: gvenzl/oracle-xe:21-slim-faststart
        ports:
        - containerPort: 1521
        env:
        - name: ORACLE_PASSWORD
          value: "Oracle123!"
        - name: APP_USER
          value: "capacityuser"
        - name: APP_USER_PASSWORD
          value: "CapacityPass123!"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: oracle-data
          mountPath: /opt/oracle/oradata
        - name: oracle-backup
          mountPath: /opt/oracle/backup
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "sqlplus -s sys/Oracle123!@localhost:1521/XE as sysdba <<< 'SELECT 1 FROM DUAL;' | grep -q '^1'"
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "sqlplus -s sys/Oracle123!@localhost:1521/XE as sysdba <<< 'SELECT 1 FROM DUAL;' | grep -q '^1'"
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
      volumes:
      - name: oracle-data
        persistentVolumeClaim:
          claimName: oracle-xe-pvc
      - name: oracle-backup
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-xe-service
spec:
  selector:
    app: oracle-xe
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521
    nodePort: 31521
  type: NodePort